/**
 * Breadcrumb label map — maps route segments (filenames) to PT-BR labels.
 * Used by core/layout/Breadcrumbs.tsx to render navigation breadcrumbs.
 */
export const breadcrumbMap: Record<string, string> = {
  /* ---- Raiz & Grupos ---- */
  "": "Início",
  home: "Início",
  Servicos: "Serviços",
  Usuario: "Usuário",
  Administrador: "Administrador",
  Notificacoes: "Notificações",

  /* ---- Administrador ---- */
  "admin-calendar": "Calendário",
  Agenda: "Agenda",
  AgendamentosPendentes: "Agendamentos Pendentes",
  "agent-channel-bindings": "Canais dos Agentes",
  "agent-dashboard": "Dashboard do Agente",
  "agent-handoff-policies": "Políticas de Handoff",
  "agent-packs": "Pacotes de Agentes",
  "agent-playbook-rules": "Regras de Playbook",
  "agent-playbook-tables": "Tabelas de Playbook",
  "agent-playbooks": "Playbooks",
  "agent-state-steps": "Etapas de Estado",
  Agents: "Agentes",
  agent_states: "Estados dos Agentes",
  "atendimento-operador": "Atendimento Operador",
  auth_codes: "Códigos de Autenticação",
  auth_tokens: "Tokens de Autenticação",
  automations: "Automações",
  AvaliacoesServico: "Avaliações de Serviço",
  "campaign-dashboard": "Painel de Campanhas",
  "campaign-items": "Conteúdos de Campanha",
  "content-pages": "Blog & Landing Pages",
  campaigns: "Campanhas",
  cartorios: "Cartórios",
  "cnpj-consulta": "Consulta CNPJ",
  companies: "Empresas",
  "company-members": "Membros da Empresa",
  "comprar-usuarios": "Planos e Assinaturas",
  ConciliadorBancario: "Conciliador Bancário",
  ContasAPagar: "Contas a Pagar",
  ContasAReceber: "Contas a Receber",
  contracts: "Contratos",
  "crm-kanban": "CRM Kanban",
  "crm-lead-detail": "Detalhe do Lead",
  "crm-leads": "Leads",
  "customer-properties": "Imóveis do Cliente",
  customers: "Clientes",
  DashboardFinanceiro: "Dashboard Financeiro",
  DRE: "DRE — Resultado",
  DisponibilidadeParceiro: "Disponibilidade do Parceiro",
  "document-generator": "Gerador de Documentos",
  "document-signatures": "Assinaturas Digitais",
  "document-templates": "Modelos de Documentos",
  "generated-documents": "Biblioteca de Documentos",
  ExecucoesServico: "Execuções de Serviço",
  Faturas: "Faturas",
  FechamentoContabil: "Fechamento Contábil",
  FolgasParceiro: "Folgas do Parceiro",
  GanhosParceiros: "Ganhos dos Parceiros",
  "gestao-de-usuarios": "Gestão de Usuários",
  "gestao-tenant": "Gestão da Organização",
  Inadimplentes: "Inadimplentes",
  "kanban-processos": "Kanban de Processos",
  "lancamentos-processos": "Lançamentos de Processos",
  "lead-forms": "Formulários de Lead",
  LogsAgendamentos: "Logs de Agendamentos",
  LogsAvaliacoes: "Logs de Avaliações",
  metabase: "Metabase (BI)",
  modulos: "Módulos",
  "ocr-config": "Configuração OCR",
  "ocr-results": "Resultados OCR",
  "onr-certidoes": "Certidões ONR",
  "onr-protocolos": "Protocolos ONR",
  Pagamentos: "Pagamentos",
  Parceiros: "Parceiros",
  permissions: "Permissões",
  permissions_sync: "Sincronizar Permissões",
  "quote-templates": "Modelos de Orçamento",
  ResumoAvaliacaoParceiro: "Resumo de Avaliação",
  roles: "Papéis",
  role_permissions: "Permissões dos Papéis",
  role_permissions_matrix: "Matriz de Permissões",
  "saas-dashboard": "Dashboard SaaS",
  "module-detail": "Módulo",
  "edit-favorites": "Editar Acesso Rápido",
  ServiceCategories: "Categorias de Serviço",
  services: "Serviços",
  ServiceTypes: "Tipos de Serviço",
  tables: "Tabelas",
  "template-editor": "Editor de Modelos",
  "template-packs": "Pacotes de Template",
  tenants: "Tenants",
  user_tenants: "Vínculos Usuário-Tenant",
  "workflow-editor": "Editor Visual de Workflow",
  workflow_steps: "Etapas do Workflow",
  workflow_templates: "Templates de Workflow",

  /* ---- Serviços (cliente) ---- */
  Ajuda: "Ajuda",
  atendimento: "Atendimento",
  Imoveis: "Imóveis",
  MeusServicos: "Meus Serviços",
  MeusTrabalhos: "Meus Trabalhos",
  MinhaAgenda: "Minha Agenda",
  MinhasAssinaturas: "Minhas Assinaturas",
  MinhasEmpresas: "Minhas Empresas",
  ParceiroCanal: "Parceiro de Canal",
  Processo: "Processo",
  servicos: "Serviços",
  SolicitarServico: "Solicitar Serviço",

  /* ---- Usuário ---- */
  CalendarSync: "Sincronização de Calendário",
  "change-password": "Alterar Senha",
  "complete-profile": "Completar Cadastro",
  "delete-account": "Excluir Conta",
  onboarding: "Configuração Inicial",
  Perfil: "Perfil",
  "selecionar-tenant": "Selecionar Empresa",

  /* ---- Notificações ---- */
  Preferencias: "Preferências",

  /* ---- Kanban sub-rotas ---- */
  "task-detail": "Detalhe da Tarefa",

  /* ---- Genéricos (modais, ações) ---- */
  modal: "Atendimento",
  property: "Imóvel",
  create: "Cadastro",
  edit: "Edição",
  settings: "Configurações",
  profile: "Perfil",
};
