export const breadcrumbMap: Record<string, string> = {
  "": "Início",
  home: "Início",
  profile: "Perfil",
  settings: "Configurações",
  modal: "Atendimento",
  property: "Imóvel",
  create: "Cadastro",
  edit: "Edição",
  Servicos: "Serviços",
  Usuario: "Usuário",
  Administrador: "Administrador",
  home: "Administração",
  servicos: "Serviços",
  atendimento: "Atendimento",
  Advogados: "Advogados",
  Regularizacao: "Regularização",
  Imoveis: "Imóveis",
  Processo: "Processo",
  "Gestao de Usuarios": "Gestão de Usuários",
  "gestao-de-usuarios": "Gestão de Usuários",
  "Lancamentos processos": "Lançamentos processos",
  tables: "Tabelas",
  tenants: "Tenants",
  Perfil: "Perfil",
  "change-password": "Alterar senha",
  "complete-profile": "Completar cadastro",
};
