import {
    ADMIN_PANEL_PERMISSIONS,
    PERMISSIONS,
    type Permission,
} from "@/core/auth/permissions";
import { Ionicons } from "@expo/vector-icons";

export type AdminPage = {
  id: string;
  group: string;
  module: "admin" | "operacao" | "cliente";
  title: string;
  description: string;
  icon: keyof typeof Ionicons.glyphMap;
  route: string;
  hidden?: boolean;
  /** Only visible to the Radul super-admin tenant (cross-tenant screens). */
  superAdminOnly?: boolean;
  requiredAnyPermissions?: Permission[];
};

export const ADMIN_PAGES: AdminPage[] = [
  {
    id: "tables",
    group: "Sistema",
    module: "admin",
    title: "Tabelas",
    description: "Consultar colunas e formatos",
    icon: "list-outline",
    route: "/Administrador/tables",
    superAdminOnly: true,
  },
  {
    id: "tenants",
    group: "Sistema",
    module: "admin",
    title: "Tenants",
    description: "Gestão de tenants",
    icon: "business-outline",
    route: "/Administrador/tenants",
    superAdminOnly: true,
  },
  {
    id: "modulos",
    group: "Sistema",
    module: "admin",
    title: "Módulos",
    description: "Ativar/desativar módulos por tenant",
    icon: "extension-puzzle-outline",
    route: "/Administrador/modulos",
    requiredAnyPermissions: [PERMISSIONS.TENANT_MANAGE],
  },
  {
    id: "template_packs",
    group: "Sistema",
    module: "admin",
    title: "Template Packs",
    description: "Configurar categorias, workflows e papéis com packs prontos",
    icon: "rocket-outline",
    route: "/Administrador/template-packs",
    requiredAnyPermissions: [PERMISSIONS.TENANT_MANAGE],
  },
  {
    id: "gestao_tenant",
    group: "Sistema",
    module: "admin",
    title: "Minha Empresa",
    description: "Plano, uso de clientes, faturamento e configurações",
    icon: "business-outline",
    route: "/Administrador/gestao-tenant",
    requiredAnyPermissions: [PERMISSIONS.TENANT_MANAGE],
  },
  {
    id: "saas_dashboard",
    group: "Sistema",
    module: "admin",
    title: "Painel SaaS",
    description: "Visão cross-tenant: tenants, usuários, módulos, crescimento",
    icon: "planet-outline",
    route: "/Administrador/saas-dashboard",
    superAdminOnly: true,
  },
  {
    id: "roles",
    group: "Acesso & Permissões",
    module: "admin",
    title: "Papéis",
    description: "Perfis e papéis de acesso",
    icon: "shield-outline",
    route: "/Administrador/roles",
    requiredAnyPermissions: [PERMISSIONS.ROLE_MANAGE],
  },
  {
    id: "permissions",
    group: "Acesso & Permissões",
    module: "admin",
    title: "Permissões",
    description: "Permissões do sistema",
    icon: "key-outline",
    route: "/Administrador/permissions",
    superAdminOnly: true,
  },
  {
    id: "permissions_sync",
    group: "Acesso & Permissões",
    module: "admin",
    title: "Sincronizar Permissões",
    description: "Criar permissões do código",
    icon: "sync-outline",
    route: "/Administrador/permissions_sync",
    hidden: true,
  },
  {
    id: "role_permissions",
    group: "Acesso & Permissões",
    module: "admin",
    title: "Permissões por Papel",
    description: "Atribuir permissões a cada papel de acesso",
    icon: "shield-checkmark-outline",
    route: "/Administrador/role_permissions",
    requiredAnyPermissions: [PERMISSIONS.ROLE_MANAGE, PERMISSIONS.PERMISSION_MANAGE],
  },
  {
    id: "role_permissions_matrix",
    group: "Acesso & Permissões",
    module: "admin",
    title: "Matriz de Permissões",
    description: "Visão consolidada de permissões por papel",
    icon: "grid-outline",
    route: "/Administrador/role_permissions_matrix",
    requiredAnyPermissions: [PERMISSIONS.ROLE_MANAGE, PERMISSIONS.PERMISSION_MANAGE],
  },
  {
    id: "auth_codes",
    group: "Sistema",
    module: "admin",
    title: "Códigos de Auth",
    description: "Códigos de autenticação emitidos",
    icon: "lock-closed-outline",
    route: "/Administrador/auth_codes",
    superAdminOnly: true,
  },
  {
    id: "auth_tokens",
    group: "Sistema",
    module: "admin",
    title: "Tokens de Auth",
    description: "Tokens de autenticação ativos",
    icon: "key-outline",
    route: "/Administrador/auth_tokens",
    superAdminOnly: true,
  },
  {
    id: "user_tenants",
    group: "Sistema",
    module: "admin",
    title: "Usuários × Tenants",
    description: "Vínculos de usuários com tenants",
    icon: "people-circle-outline",
    route: "/Administrador/user_tenants",
    superAdminOnly: true,
  },
  {
    id: "comprar_usuarios",
    group: "Sistema",
    module: "admin",
    title: "Comprar Usuários",
    description: "Adicionar vagas de usuários ao plano",
    icon: "person-add-outline",
    route: "/Administrador/comprar-usuarios",
    requiredAnyPermissions: [PERMISSIONS.TENANT_MANAGE],
  },
  {
    id: "edit_favorites",
    group: "Sistema",
    module: "admin",
    title: "Editar Favoritos",
    description: "Personalizar atalhos e favoritos do menu",
    icon: "star-outline",
    route: "/Administrador/edit-favorites",
    hidden: true,
  },
  {
    id: "module_detail",
    group: "Sistema",
    module: "admin",
    title: "Detalhe do Módulo",
    description: "Informações e configuração de um módulo específico",
    icon: "extension-puzzle-outline",
    route: "/Administrador/module-detail",
    hidden: true,
    requiredAnyPermissions: ADMIN_PANEL_PERMISSIONS,
  },
  {
    id: "services_crud",
    group: "Serviços & Produtos",
    module: "operacao",
    title: "Serviços e Produtos",
    description: "Catálogo de serviços e produtos oferecidos",
    icon: "construct-outline",
    route: "/Administrador/services",
    requiredAnyPermissions: [PERMISSIONS.SERVICE_READ],
  },
  {
    id: "composicoes",
    group: "Serviços & Produtos",
    module: "operacao",
    title: "Composições",
    description: "Combos e kits de produtos/serviços",
    icon: "layers-outline",
    route: "/Administrador/Composicoes",
    requiredAnyPermissions: [PERMISSIONS.SERVICE_READ],
  },
  {
    id: "regras_desconto",
    group: "Vendas & PDV",
    module: "operacao",
    title: "Regras de Desconto",
    description: "Limites de desconto por papel",
    icon: "pricetag-outline",
    route: "/Administrador/RegrasDesconto",
    requiredAnyPermissions: [PERMISSIONS.SALE_WRITE],
  },
  {
    id: "pdv",
    group: "Vendas & PDV",
    module: "operacao",
    title: "Ponto de Venda",
    description: "PDV — venda direta de produtos e serviços",
    icon: "cart-outline",
    route: "/Servicos/PDV",
    requiredAnyPermissions: [PERMISSIONS.PDV_ACCESS],
  },
  {
    id: "pre_venda",
    group: "Vendas & PDV",
    module: "operacao",
    title: "Pré-Venda",
    description: "Comandas abertas — adicione itens e feche depois no caixa",
    icon: "clipboard-outline",
    route: "/Servicos/PreVenda",
    requiredAnyPermissions: [PERMISSIONS.PRESALE_READ],
  },
  {
    id: "vendas",
    group: "Vendas & PDV",
    module: "operacao",
    title: "Vendas",
    description: "Gestão de todas as vendas (produtos e serviços)",
    icon: "receipt-outline",
    route: "/Administrador/Vendas",
    requiredAnyPermissions: [PERMISSIONS.SALE_READ],
  },
  {
    id: "minhas_vendas",
    group: "Vendas & PDV",
    module: "operacao",
    title: "Minhas Vendas",
    description: "Histórico das suas vendas realizadas",
    icon: "receipt-outline",
    route: "/Servicos/MinhasVendas",
    requiredAnyPermissions: [PERMISSIONS.SALE_READ],
  },
  {
    id: "estoque",
    group: "Estoque & Compras",
    module: "operacao",
    title: "Estoque",
    description: "Posição de estoque dos produtos",
    icon: "cube-outline",
    route: "/Administrador/Estoque",
    requiredAnyPermissions: [PERMISSIONS.STOCK_READ],
  },
  {
    id: "movimentacoes_estoque",
    group: "Estoque & Compras",
    module: "operacao",
    title: "Movimentações",
    description: "Histórico de entradas e saídas do estoque",
    icon: "swap-horizontal-outline",
    route: "/Administrador/MovimentacoesEstoque",
    requiredAnyPermissions: [PERMISSIONS.STOCK_READ],
  },
  {
    id: "fornecedores",
    group: "Estoque & Compras",
    module: "operacao",
    title: "Fornecedores",
    description: "Cadastro de fornecedores",
    icon: "business-outline",
    route: "/Administrador/Fornecedores",
    requiredAnyPermissions: [PERMISSIONS.SUPPLIER_READ],
  },
  {
    id: "solicitacoes_compras",
    group: "Estoque & Compras",
    module: "operacao",
    title: "Solicitacoes de Compras",
    description: "Requisicoes internas para aprovacao e compra",
    icon: "clipboard-outline",
    route: "/Administrador/SolicitacoesCompras",
    requiredAnyPermissions: [PERMISSIONS.PURCHASE_WRITE],
  },
  {
    id: "compras",
    group: "Estoque & Compras",
    module: "operacao",
    title: "Compras",
    description: "Pedidos de compra e recebimento de mercadorias",
    icon: "cart-outline",
    route: "/Administrador/Compras",
    requiredAnyPermissions: [PERMISSIONS.PURCHASE_READ],
  },
  {
    id: "separacao",
    group: "Vendas & PDV",
    module: "operacao",
    title: "Separação",
    description: "Kanban de separação de pedidos (pending → ready)",
    icon: "git-branch-outline",
    route: "/Administrador/Separacao",
    requiredAnyPermissions: [PERMISSIONS.SALE_READ],
  },
  {
    id: "agendamentos_pendentes",
    group: "Vendas & PDV",
    module: "operacao",
    title: "Agendamentos Pendentes",
    description:
      "Kanban de serviços vendidos aguardando agendamento e execução",
    icon: "calendar-outline",
    route: "/Administrador/AgendamentosPendentes",
    requiredAnyPermissions: [PERMISSIONS.SALE_READ],
  },
  {
    id: "marketplace_config",
    group: "Vendas & PDV",
    module: "operacao",
    title: "Loja Online",
    description: "Configurar marketplace, PIX, frete e catálogo público",
    icon: "storefront-outline",
    route: "/Administrador/marketplace-config",
    requiredAnyPermissions: [PERMISSIONS.SALE_WRITE],
  },
  {
    id: "service_categories",
    group: "Serviços & Produtos",
    module: "admin",
    title: "Categorias",
    description: "Gestão de categorias de serviços e produtos",
    icon: "albums-outline",
    route: "/Administrador/ServiceCategories",
    requiredAnyPermissions: [PERMISSIONS.SERVICE_READ],
  },
  {
    id: "service_types",
    group: "Serviços & Produtos",
    module: "cliente",
    title: "Tipos de Serviço",
    description: "Tipos de serviços dentro das categorias",
    icon: "list-outline",
    route: "/Administrador/ServiceTypes",
    requiredAnyPermissions: [PERMISSIONS.SERVICE_READ],
  },
  {
    id: "agenda",
    group: "Agenda",
    module: "operacao",
    title: "Calendário Geral",
    description: "Visão consolidada de todos os eventos e agendamentos",
    icon: "calendar",
    route: "/Administrador/admin-calendar",
    requiredAnyPermissions: [PERMISSIONS.TASK_READ, PERMISSIONS.APPOINTMENT_READ],
  },
  {
    id: "avaliacoes",
    group: "Serviços & Produtos",
    module: "cliente",
    title: "Avaliações",
    description: "Gestão de reviews de serviços e produtos",
    icon: "star-outline",
    route: "/Administrador/AvaliacoesServico",
    requiredAnyPermissions: [PERMISSIONS.CUSTOMER_READ],
  },
  {
    id: "customers",
    group: "Clientes & Usuários",
    module: "cliente",
    title: "Clientes",
    description: "Gestão de clientes e imóveis vinculados",
    icon: "people-outline",
    route: "/Administrador/customers",
    requiredAnyPermissions: [PERMISSIONS.CUSTOMER_READ],
  },
  {
    id: "companies",
    group: "Clientes & Usuários",
    module: "cliente",
    title: "Empresas",
    description: "Gestão de empresas (CNPJ) e membros",
    icon: "business-outline",
    route: "/Administrador/companies",
    requiredAnyPermissions: [PERMISSIONS.COMPANY_READ, PERMISSIONS.CUSTOMER_READ],
  },
  {
    id: "atendimento_operador",
    group: "Clientes & Usuários",
    module: "cliente",
    title: "Atendimento Operador",
    description: "Chat manual com cliente",
    icon: "chatbubbles-outline",
    route: "/Administrador/atendimento-operador",
    requiredAnyPermissions: [
      PERMISSIONS.ATENDIMENTO_READ,
      PERMISSIONS.ATENDIMENTO_WRITE,
    ],
  },
  {
    id: "dashboard_atendimento",
    group: "Clientes & Usuários",
    module: "cliente",
    title: "Dashboard Atendimento",
    description: "KPIs e métricas de atendimento ao cliente",
    icon: "bar-chart-outline",
    route: "/Administrador/DashboardAtendimento",
    requiredAnyPermissions: [
      PERMISSIONS.ATENDIMENTO_DASHBOARD,
      PERMISSIONS.ATENDIMENTO_READ,
    ],
  },
  {
    id: "cnpj_consulta",
    group: "Clientes & Usuários",
    module: "cliente",
    title: "Consulta CNPJ",
    description: "Buscar dados de empresa por CNPJ",
    icon: "search-outline",
    route: "/Administrador/cnpj-consulta",
    requiredAnyPermissions: [
      PERMISSIONS.CUSTOMER_READ,
      PERMISSIONS.COMPANY_READ,
    ],
  },
  {
    id: "company_members",
    group: "Clientes & Usuários",
    module: "cliente",
    title: "Membros da Empresa",
    description: "Sócios e representantes da empresa",
    icon: "people-outline",
    route: "/Administrador/company-members",
    hidden: true,
    requiredAnyPermissions: [
      PERMISSIONS.COMPANY_READ,
      PERMISSIONS.COMPANY_WRITE,
    ],
  },
  {
    id: "customer_contracts",
    group: "Clientes & Usuários",
    module: "cliente",
    title: "Contratos do Cliente",
    description: "Contratos vinculados a um cliente",
    icon: "reader-outline",
    route: "/Administrador/customer-contracts",
    hidden: true,
    requiredAnyPermissions: [PERMISSIONS.CUSTOMER_READ],
  },
  {
    id: "customer_payments",
    group: "Clientes & Usuários",
    module: "operacao",
    title: "Pagamentos do Cliente",
    description: "Histórico de pagamentos de um cliente",
    icon: "card-outline",
    route: "/Administrador/customer-payments",
    hidden: true,
    requiredAnyPermissions: [
      PERMISSIONS.CUSTOMER_READ,
      PERMISSIONS.FINANCIAL_READ,
    ],
  },
  {
    id: "customer_processes",
    group: "Clientes & Usuários",
    module: "cliente",
    title: "Processos do Cliente",
    description: "Ordens de serviço vinculadas a um cliente",
    icon: "briefcase-outline",
    route: "/Administrador/customer-processes",
    hidden: true,
    requiredAnyPermissions: [PERMISSIONS.CUSTOMER_READ],
  },
  {
    id: "customer_properties",
    group: "Clientes & Usuários",
    module: "cliente",
    title: "Imóveis do Cliente",
    description: "Imóveis vinculados a um cliente",
    icon: "home-outline",
    route: "/Administrador/customer-properties",
    hidden: true,
    requiredAnyPermissions: [PERMISSIONS.CUSTOMER_READ],
  },
  {
    id: "customer_quotes",
    group: "Clientes & Usuários",
    module: "cliente",
    title: "Orçamentos do Cliente",
    description: "Orçamentos emitidos para um cliente",
    icon: "document-text-outline",
    route: "/Administrador/customer-quotes",
    hidden: true,
    requiredAnyPermissions: [PERMISSIONS.CUSTOMER_READ],
  },
  {
    id: "customer_sales",
    group: "Clientes & Usuários",
    module: "operacao",
    title: "Vendas do Cliente",
    description: "Vendas realizadas para um cliente",
    icon: "receipt-outline",
    route: "/Administrador/customer-sales",
    hidden: true,
    requiredAnyPermissions: [PERMISSIONS.CUSTOMER_READ, PERMISSIONS.SALE_READ],
  },
  {
    id: "parceiros",
    group: "Parceiros",
    module: "operacao",
    title: "Parceiros",
    description: "Gestão de parceiros",
    icon: "people-outline",
    route: "/Administrador/Parceiros",
    requiredAnyPermissions: [
      PERMISSIONS.PARTNER_READ,
      PERMISSIONS.PARTNER_WRITE,
    ],
  },
  {
    id: "ganhos_parceiros",
    group: "Parceiros",
    module: "operacao",
    title: "Ganhos de Parceiros",
    description: "Comissões, bônus e pagamentos a parceiros",
    icon: "wallet-outline",
    route: "/Administrador/GanhosParceiros",
    requiredAnyPermissions: [
      PERMISSIONS.PARTNER_READ,
      PERMISSIONS.FINANCIAL_READ,
    ],
  },
  {
    id: "meus_trabalhos",
    group: "Parceiros",
    module: "operacao",
    title: "Meus Trabalhos",
    description: "Agendamentos atribuídos a você como parceiro",
    icon: "hammer-outline",
    route: "/Servicos/MeusTrabalhos",
    requiredAnyPermissions: [PERMISSIONS.PARTNER_READ],
  },
  {
    id: "channel_partners",
    group: "Parceiros",
    module: "operacao",
    title: "Parceiros de Canal",
    description: "Revendedores SaaS — apenas Radul",
    icon: "share-social-outline",
    route: "/Administrador/channel-partners",
    superAdminOnly: true,
    requiredAnyPermissions: [
      PERMISSIONS.PARTNER_READ,
      PERMISSIONS.PARTNER_WRITE,
    ],
  },
  {
    id: "channel_partner_dashboard",
    group: "Parceiros",
    module: "operacao",
    title: "Dashboard de Parcerias",
    description: "Métricas de indicações e comissões — apenas Radul",
    icon: "trending-up-outline",
    route: "/Administrador/channel-partner-dashboard",
    superAdminOnly: true,
    requiredAnyPermissions: [
      PERMISSIONS.PARTNER_READ,
      PERMISSIONS.FINANCIAL_READ,
    ],
  },
  {
    id: "disponibilidade_parceiro",
    group: "Parceiros",
    module: "operacao",
    title: "Disponibilidade do Parceiro",
    description: "Horários e dias disponíveis de cada parceiro",
    icon: "calendar-outline",
    route: "/Administrador/DisponibilidadeParceiro",
    requiredAnyPermissions: [
      PERMISSIONS.PARTNER_READ,
      PERMISSIONS.PARTNER_WRITE,
    ],
  },
  {
    id: "folgas_parceiro",
    group: "Parceiros",
    module: "operacao",
    title: "Folgas do Parceiro",
    description: "Folgas, férias e ausências de parceiros",
    icon: "sunny-outline",
    route: "/Administrador/FolgasParceiro",
    requiredAnyPermissions: [
      PERMISSIONS.PARTNER_READ,
      PERMISSIONS.PARTNER_WRITE,
    ],
  },
  {
    id: "execucoes_servico",
    group: "Parceiros",
    module: "operacao",
    title: "Execuções de Serviço",
    description: "Registro de execuções de serviço por parceiros",
    icon: "construct-outline",
    route: "/Administrador/ExecucoesServico",
    requiredAnyPermissions: [
      PERMISSIONS.PARTNER_READ,
      PERMISSIONS.PROCESS_READ,
    ],
  },
  {
    id: "resumo_avaliacao_parceiro",
    group: "Parceiros",
    module: "operacao",
    title: "Resumo de Avaliações",
    description: "Resumo das avaliações e ratings de parceiros",
    icon: "star-outline",
    route: "/Administrador/ResumoAvaliacaoParceiro",
    requiredAnyPermissions: [PERMISSIONS.PARTNER_READ],
  },
  {
    id: "logs_avaliacoes",
    group: "Parceiros",
    module: "operacao",
    title: "Logs de Avaliações",
    description: "Histórico detalhado de avaliações de serviço",
    icon: "chatbox-ellipses-outline",
    route: "/Administrador/LogsAvaliacoes",
    requiredAnyPermissions: [PERMISSIONS.PARTNER_READ],
  },
  {
    id: "logs_agendamentos",
    group: "Parceiros",
    module: "operacao",
    title: "Logs de Agendamentos",
    description: "Histórico de agendamentos e alterações de horário",
    icon: "time-outline",
    route: "/Administrador/LogsAgendamentos",
    requiredAnyPermissions: [PERMISSIONS.PARTNER_READ],
  },
  {
    id: "servicos_parceiro",
    group: "Parceiros",
    module: "operacao",
    title: "Serviços por Parceiro",
    description: "Serviços atribuídos e executados por cada parceiro",
    icon: "briefcase-outline",
    route: "/Administrador/ServicosParceiro",
    requiredAnyPermissions: [PERMISSIONS.PARTNER_READ],
  },

  // ---- Financeiro ----
  {
    id: "recebimentos_config",
    group: "Financeiro",
    module: "operacao",
    title: "Recebimentos",
    description: "Habilitar PIX e cartao e configurar gateway",
    icon: "wallet-outline",
    route: "/Administrador/recebimentos-config",
    requiredAnyPermissions: [
      PERMISSIONS.FINANCIAL_READ,
      PERMISSIONS.FINANCIAL_WRITE,
    ],
  },
  {
    id: "split_servicos",
    group: "Financeiro",
    module: "operacao",
    title: "Splits por Servico",
    description: "Regras de divisao por servico e parceiro",
    icon: "git-branch-outline",
    route: "/Administrador/split-servicos",
    requiredAnyPermissions: [
      PERMISSIONS.FINANCIAL_READ,
      PERMISSIONS.FINANCIAL_WRITE,
    ],
  },
  {
    id: "dashboard_financeiro",
    group: "Financeiro",
    module: "operacao",
    title: "Dashboard Financeiro",
    description: "KPIs, receita mensal, transações recentes",
    icon: "stats-chart-outline",
    route: "/Administrador/DashboardFinanceiro",
    requiredAnyPermissions: [
      PERMISSIONS.FINANCIAL_DASHBOARD,
      PERMISSIONS.FINANCIAL_READ,
    ],
  },
  {
    id: "dre",
    group: "Financeiro",
    module: "operacao",
    title: "DRE — Resultado",
    description: "Receita × Custo por período e tipo (produtos vs serviços)",
    icon: "bar-chart-outline",
    route: "/Administrador/DRE",
    requiredAnyPermissions: [
      PERMISSIONS.FINANCIAL_DASHBOARD,
      PERMISSIONS.FINANCIAL_READ,
    ],
  },
  {
    id: "contas_a_receber",
    group: "Financeiro",
    module: "operacao",
    title: "Contas a Receber",
    description: "Recebíveis de clientes, faturas e serviços",
    icon: "trending-up-outline",
    route: "/Administrador/ContasAReceber",
    requiredAnyPermissions: [
      PERMISSIONS.FINANCIAL_READ,
      PERMISSIONS.FINANCIAL_WRITE,
    ],
  },
  {
    id: "contas_a_pagar",
    group: "Financeiro",
    module: "operacao",
    title: "Contas a Pagar",
    description: "Despesas, pagamentos a parceiros, impostos",
    icon: "trending-down-outline",
    route: "/Administrador/ContasAPagar",
    requiredAnyPermissions: [
      PERMISSIONS.FINANCIAL_READ,
      PERMISSIONS.FINANCIAL_WRITE,
    ],
  },
  {
    id: "faturas",
    group: "Financeiro",
    module: "operacao",
    title: "Faturas",
    description: "Emissão e gestão de faturas com PIX",
    icon: "receipt-outline",
    route: "/Administrador/Faturas",
    requiredAnyPermissions: [
      PERMISSIONS.FINANCIAL_READ,
      PERMISSIONS.FINANCIAL_WRITE,
    ],
  },
  {
    id: "pagamentos",
    group: "Financeiro",
    module: "operacao",
    title: "Pagamentos",
    description: "Registro de pagamentos recebidos e efetuados",
    icon: "card-outline",
    route: "/Administrador/Pagamentos",
    requiredAnyPermissions: [
      PERMISSIONS.FINANCIAL_READ,
      PERMISSIONS.FINANCIAL_WRITE,
    ],
  },
  {
    id: "inadimplentes",
    group: "Financeiro",
    module: "operacao",
    title: "Inadimplentes",
    description: "Gestão de clientes com pagamentos em atraso",
    icon: "warning-outline",
    route: "/Administrador/Inadimplentes",
    requiredAnyPermissions: [
      PERMISSIONS.DELINQUENCY_READ,
      PERMISSIONS.DELINQUENCY_WRITE,
    ],
  },
  {
    id: "conciliador_bancario",
    group: "Financeiro",
    module: "operacao",
    title: "Conciliador Bancário",
    description:
      "Importe OFX do banco e concilie transações com recebíveis e despesas",
    icon: "git-compare-outline",
    route: "/Administrador/ConciliadorBancario",
    requiredAnyPermissions: [
      PERMISSIONS.FINANCIAL_READ,
      PERMISSIONS.FINANCIAL_WRITE,
    ],
  },
  {
    id: "fechamento_contabil",
    group: "Financeiro",
    module: "operacao",
    title: "Fechamento Contábil",
    description:
      "Exportação mensal de documentos financeiros para enviar ao contador",
    icon: "cloud-download-outline",
    route: "/Administrador/FechamentoContabil",
    requiredAnyPermissions: [
      PERMISSIONS.FINANCIAL_READ,
      PERMISSIONS.FINANCIAL_DASHBOARD,
    ],
  },
  {
    id: "usuarios",
    group: "Clientes & Usuários",
    module: "cliente",
    title: "Gestão de usuários",
    description: "Clientes e imóveis vinculados",
    icon: "people-outline",
    route: "/Administrador/gestao-de-usuarios",
    requiredAnyPermissions: [PERMISSIONS.USER_READ, PERMISSIONS.USER_MANAGE],
  },
  {
    id: "processos",
    group: "Operação",
    module: "operacao",
    title: "Lançamento de processo",
    description: "Publicação de atualizações",
    icon: "briefcase-outline",
    route: "/Administrador/lancamentos-processos",
    hidden: true,
  },

  {
    id: "agent_packs",
    group: "Automação & Workflows",
    module: "admin",
    title: "Packs de Agentes IA",
    description: "Configurar agentes, playbooks e estados com packs prontos",
    icon: "sparkles-outline",
    route: "/Administrador/agent-packs",
    requiredAnyPermissions: [PERMISSIONS.AGENT_MANAGE],
  },
  {
    id: "agents",
    group: "Automação & Workflows",
    module: "admin",
    title: "Agentes IA",
    description: "Gestão de agentes de atendimento",
    icon: "boat-outline",
    route: "/Administrador/Agents",
    requiredAnyPermissions: [PERMISSIONS.AGENT_MANAGE],
  },
  {
    id: "agent_playbooks",
    group: "Automação & Workflows",
    module: "admin",
    title: "Playbooks do Agent",
    description: "Comportamento do robô por tenant e canal",
    icon: "book-outline",
    route: "/Administrador/agent-playbooks",
    requiredAnyPermissions: [PERMISSIONS.AGENT_MANAGE],
  },
  {
    id: "agent_playbook_rules",
    group: "Automação & Workflows",
    module: "admin",
    title: "Regras do Playbook",
    description: "Instruções e regras de execução do robô",
    icon: "list-circle-outline",
    route: "/Administrador/agent-playbook-rules",
    requiredAnyPermissions: [PERMISSIONS.AGENT_MANAGE],
  },
  {
    id: "agent_playbook_tables",
    group: "Automação & Workflows",
    module: "admin",
    title: "Tabelas do Playbook",
    description: "Escopo de tabelas configuráveis no módulo IA",
    icon: "server-outline",
    route: "/Administrador/agent-playbook-tables",
    requiredAnyPermissions: [PERMISSIONS.AGENT_MANAGE],
  },
  {
    id: "agent_handoff_policies",
    group: "Automação & Workflows",
    module: "admin",
    title: "Políticas de Handoff",
    description: "Transição bot ↔ operador e retorno ao state",
    icon: "swap-horizontal-outline",
    route: "/Administrador/agent-handoff-policies",
    requiredAnyPermissions: [PERMISSIONS.AGENT_MANAGE],
  },
  {
    id: "agent_state_steps",
    group: "Automação & Workflows",
    module: "admin",
    title: "Passos por Estado",
    description: "Sequência guiada por state_key do atendimento",
    icon: "footsteps-outline",
    route: "/Administrador/agent-state-steps",
    requiredAnyPermissions: [PERMISSIONS.AGENT_MANAGE],
  },
  {
    id: "agent_channel_bindings",
    group: "Automação & Workflows",
    module: "admin",
    title: "Bindings de Canal",
    description: "Webhook por canal para cada agent",
    icon: "link-outline",
    route: "/Administrador/agent-channel-bindings",
    requiredAnyPermissions: [PERMISSIONS.AGENT_MANAGE],
  },
  {
    id: "agent_dashboard",
    group: "Automação & Workflows",
    module: "admin",
    title: "Dashboard de Agentes",
    description: "Visão geral dos agentes IA, estados e métricas",
    icon: "analytics-outline",
    route: "/Administrador/agent-dashboard",
    requiredAnyPermissions: [PERMISSIONS.AGENT_MANAGE],
  },
  {
    id: "agent_states",
    group: "Automação & Workflows",
    module: "admin",
    title: "Estados de Agentes",
    description: "Configuração de estados e máquina de estados dos agentes",
    icon: "toggle-outline",
    route: "/Administrador/agent_states",
    requiredAnyPermissions: [PERMISSIONS.AGENT_MANAGE],
  },
  {
    id: "automations",
    group: "Automação & Workflows",
    module: "admin",
    title: "Automações",
    description: "Regras de automação e execuções programadas",
    icon: "flash-outline",
    route: "/Administrador/automations",
    requiredAnyPermissions: [PERMISSIONS.AUTOMATION_MANAGE],
  },
  {
    id: "workflow_templates",
    group: "Automação & Workflows",
    module: "admin",
    title: "Templates de Workflow",
    description: "Gestão de templates de workflow",
    icon: "git-branch-outline",
    route: "/Administrador/workflow_templates",
    requiredAnyPermissions: [PERMISSIONS.WORKFLOW_READ],
  },
  {
    id: "workflow_editor",
    group: "Automação & Workflows",
    module: "admin",
    title: "Editor Visual de Workflow",
    description: "Editor visual de etapas, transições, formulários e tarefas",
    icon: "git-network-outline",
    route: "/Administrador/workflow-editor",
    requiredAnyPermissions: [PERMISSIONS.WORKFLOW_READ, PERMISSIONS.WORKFLOW_WRITE],
  },
  {
    id: "workflow_steps",
    group: "Automação & Workflows",
    module: "admin",
    title: "Etapas do Workflow",
    description: "Gestão de etapas do workflow (lista)",
    icon: "list-outline",
    route: "/Administrador/workflow_steps",
    requiredAnyPermissions: [PERMISSIONS.WORKFLOW_READ],
  },
  {
    id: "servicos_workflow",
    group: "Automação & Workflows",
    module: "operacao",
    title: "Serviços & Workflow",
    description: "Vínculo entre tipos de serviço e templates de workflow",
    icon: "git-merge-outline",
    route: "/Administrador/ServicosWorkflow",
    requiredAnyPermissions: [PERMISSIONS.SERVICE_READ, PERMISSIONS.WORKFLOW_READ],
  },
  {
    id: "kanban_processos",
    group: "Operação",
    module: "operacao",
    title: "Kanban de Processos",
    description: "Gestão de processos, tarefas, avanço de etapas e lançamentos",
    icon: "grid-outline",
    route: "/Administrador/kanban-processos",
    requiredAnyPermissions: [PERMISSIONS.TASK_READ, PERMISSIONS.WORKFLOW_READ],
  },
  {
    id: "metabase",
    group: "Auditoria & Logs",
    module: "admin",
    title: "BI — Metabase",
    description: "Relatórios e dashboards do tenant",
    icon: "bar-chart-outline",
    route: "/Administrador/metabase",
    requiredAnyPermissions: [PERMISSIONS.FINANCIAL_DASHBOARD],
  },
  {
    id: "notifications",
    group: "Auditoria & Logs",
    module: "admin",
    title: "Notificações",
    description: "Gerenciar notificações",
    icon: "notifications-outline",
    route: "/Notificacoes",
  },
  {
    id: "onr_protocolos",
    group: "Documentos & OCR",
    module: "operacao",
    title: "Protocolos",
    description: "Documentação consolidada para envio ao cartório",
    icon: "receipt-outline",
    route: "/Administrador/onr-protocolos",
    requiredAnyPermissions: [PERMISSIONS.DOCUMENT_READ],
  },
  {
    id: "onr_certidoes",
    group: "Documentos & OCR",
    module: "operacao",
    title: "Certidões",
    description: "Documentos finais e certidões emitidas pelo cartório",
    icon: "ribbon-outline",
    route: "/Administrador/onr-certidoes",
    requiredAnyPermissions: [PERMISSIONS.DOCUMENT_READ],
  },
  {
    id: "cartorios",
    group: "Documentos & OCR",
    module: "admin",
    title: "Cartórios",
    description: "Cadastro de cartórios e serventias",
    icon: "storefront-outline",
    route: "/Administrador/cartorios",
    requiredAnyPermissions: [PERMISSIONS.DOCUMENT_READ],
  },
  {
    id: "document_signatures",
    group: "Documentos & OCR",
    module: "operacao",
    title: "Assinaturas Digitais",
    description: "Gestão de assinaturas via Documenso",
    icon: "document-text-outline",
    route: "/Administrador/document-signatures",
    requiredAnyPermissions: [PERMISSIONS.DOCUMENT_READ],
  },
  {
    id: "ocr_config",
    group: "Documentos & OCR",
    module: "admin",
    title: "Configuração OCR",
    description: "Regras de análise automática de documentos",
    icon: "scan-outline",
    route: "/Administrador/ocr-config",
    requiredAnyPermissions: [PERMISSIONS.DOCUMENT_READ],
  },
  {
    id: "ocr_results",
    group: "Documentos & OCR",
    module: "admin",
    title: "Resultados OCR",
    description: "Textos e dados extraídos de documentos",
    icon: "eye-outline",
    route: "/Administrador/ocr-results",
    requiredAnyPermissions: [PERMISSIONS.DOCUMENT_READ],
  },
  {
    id: "document_templates",
    group: "Documentos & OCR",
    module: "operacao",
    title: "Modelos de Documentos",
    description: "Criar e gerenciar modelos de documentos com variáveis",
    icon: "document-outline",
    route: "/Administrador/document-templates",
    requiredAnyPermissions: [PERMISSIONS.DOCUMENT_READ],
  },
  {
    id: "generated_documents",
    group: "Documentos & OCR",
    module: "operacao",
    title: "Biblioteca de Documentos",
    description: "Ver, editar rascunhos e gerenciar documentos gerados",
    icon: "library-outline",
    route: "/Administrador/generated-documents",
    requiredAnyPermissions: [PERMISSIONS.DOCUMENT_READ],
  },
  {
    id: "document_generator",
    group: "Documentos & OCR",
    module: "operacao",
    title: "Gerar Documento",
    description: "Preencher variáveis e gerar PDF a partir de modelo",
    icon: "print-outline",
    route: "/Administrador/document-generator",
    requiredAnyPermissions: [PERMISSIONS.DOCUMENT_READ, PERMISSIONS.DOCUMENT_WRITE],
  },
  {
    id: "template_editor",
    group: "Documentos & OCR",
    module: "operacao",
    title: "Editor de Templates",
    description: "Edição visual de modelos de documentos com variáveis",
    icon: "create-outline",
    route: "/Administrador/template-editor",
    requiredAnyPermissions: [PERMISSIONS.DOCUMENT_READ, PERMISSIONS.DOCUMENT_WRITE],
  },

  // ---- CRM & Leads ----
  {
    id: "crm_kanban",
    group: "CRM & Leads",
    module: "operacao",
    title: "Pipeline de Leads",
    description: "Kanban do funil de vendas com etapas do pipeline",
    icon: "funnel-outline",
    route: "/Administrador/crm-kanban",
    requiredAnyPermissions: [PERMISSIONS.CUSTOMER_READ],
  },
  {
    id: "crm_lead_detail",
    group: "CRM & Leads",
    module: "operacao",
    title: "Detalhe do Lead",
    description: "Visão completa do lead com timeline e ações",
    icon: "person-circle-outline",
    route: "/Administrador/crm-lead-detail",
    hidden: true,
  },
  {
    id: "crm_leads",
    group: "CRM & Leads",
    module: "operacao",
    title: "Leads",
    description: "Lista completa de leads com busca e filtros",
    icon: "people-circle-outline",
    route: "/Administrador/crm-leads",
    requiredAnyPermissions: [PERMISSIONS.CUSTOMER_READ],
  },
  {
    id: "campaigns",
    group: "CRM & Leads",
    module: "operacao",
    title: "Campanhas",
    description: "Gestão de campanhas de marketing e divulgação",
    icon: "megaphone-outline",
    route: "/Administrador/campaigns",
    requiredAnyPermissions: [PERMISSIONS.CUSTOMER_READ],
  },
  {
    id: "campaign_dashboard",
    group: "CRM & Leads",
    module: "operacao",
    title: "Dashboard de Campanhas",
    description: "Funil de marketing, ROI e desempenho por canal",
    icon: "bar-chart-outline",
    route: "/Administrador/campaign-dashboard",
    requiredAnyPermissions: [PERMISSIONS.CUSTOMER_READ],
  },
  {
    id: "campaign_items",
    group: "CRM & Leads",
    module: "operacao",
    title: "Conteúdos de Campanha",
    description: "Posts, blogs, anúncios e conteúdos das campanhas",
    icon: "documents-outline",
    route: "/Administrador/campaign-items",
    requiredAnyPermissions: [PERMISSIONS.CUSTOMER_READ],
  },
  {
    id: "lead_forms",
    group: "CRM & Leads",
    module: "operacao",
    title: "Formulários de Captação",
    description: "Formulários públicos para captar leads automaticamente",
    icon: "document-text-outline",
    route: "/Administrador/lead-forms",
    requiredAnyPermissions: [PERMISSIONS.CUSTOMER_READ],
  },
  {
    id: "content_pages",
    group: "CRM & Leads",
    module: "operacao",
    title: "Blog & Landing Pages",
    description: "Blog público e landing pages com CTA de captação",
    icon: "newspaper-outline",
    route: "/Administrador/content-pages",
    requiredAnyPermissions: [PERMISSIONS.CUSTOMER_READ],
  },
  {
    id: "perfil_marketing",
    group: "CRM & Leads",
    module: "operacao",
    title: "Perfil de Marketing",
    description: "Configure o perfil da marca para gerar conteúdo com IA",
    icon: "color-palette-outline",
    route: "/Administrador/perfil-marketing",
    requiredAnyPermissions: [PERMISSIONS.CUSTOMER_READ],
  },

  // ---- Orçamentos ----
  {
    id: "quote_templates",
    group: "Orçamentos",
    module: "operacao",
    title: "Templates de Orçamento",
    description: "Modelos reutilizáveis para criar orçamentos rapidamente",
    icon: "copy-outline",
    route: "/Administrador/quote-templates",
    requiredAnyPermissions: [PERMISSIONS.FINANCIAL_READ],
  },
  {
    id: "quotes",
    group: "Orçamentos",
    module: "operacao",
    title: "Orçamentos",
    description: "Gerencie orçamentos enviados e acompanhe aprovações",
    icon: "document-text-outline",
    route: "/Administrador/orcamentos",
    requiredAnyPermissions: [PERMISSIONS.FINANCIAL_READ],
  },

  // ---- Contratos ----
  {
    id: "contracts",
    group: "Contratos",
    module: "operacao",
    title: "Contratos",
    description: "Gestão de contratos, SLA e renovações automáticas",
    icon: "reader-outline",
    route: "/Administrador/contracts",
    requiredAnyPermissions: [PERMISSIONS.CUSTOMER_READ, PERMISSIONS.FINANCIAL_READ],
  },
  {
    id: "contract-detail",
    group: "Contratos",
    module: "operacao",
    title: "Detalhes do Contrato",
    description: "Dashboard detalhado do contrato",
    icon: "reader-outline",
    route: "/Administrador/contract-detail",
    hidden: true,
  },
];
